### ISSUE TITLE
Unit Test Error

### ISSUE THREAD

**Issue by mtsrst** [cyber-z/public-fox-android-sdk#12]
v2.15.7g をUnit Testをしたところ、java.lang.VerifyError が発生。
環境は、robolectric, retrolambda を使用。
```
java.lang.VerifyError: Expecting a stackmap frame at branch target xxx
Exception Details:
  Location:
    jp/appAdForce/android/InstallReceiver.a(Landroid/content/Context;Landroid/content/Intent;)V @4: aload_1
  Reason:
    Expected stackmap frame at this location.
```

**Comment by czwuwei** [comment]
標準以外の環境との互換性を対応することが難しいため、
基本的には保証しておりません。

https://github.com/robolectric/robolectric/issues/1186
https://github.com/robolectric/robolectric-gradle-plugin/issues/144
http://stackoverflow.com/questions/15253173/how-safe-is-it-to-use-xx-usesplitverifier?answertab=votes#tab-top
こちらを参照して、
`XX:-UseSplitVerifier`のworkaroundを試して頂けますでしょうか？

**Comment by lapastillaroja** [comment]
`XX:-UseSplitVerifier`について、検討させてください。

ちなみに、`標準以外の環境`について、標準環境とはなんですか

**Comment by czwuwei** [comment]
Android公式 SDKのrelease versionを使用してテストしているため、標準環境としてはAndroid 公式SDKになります。

調べまして、`robolectric`はbytecodeベースでclassを操作しているようなので、
もしかしたら標準のAndroid SDKでコンパイルしたclassファイルと同じ動作にならない可能性があるかなと考えています。

**Comment by lapastillaroja** [comment]
@czwuwei 
返事遅くなってすみません。いったん以下のように対応しました
```groovy
    testOptions {
        unitTests {
            all {
                // configure the test JVM arguments
                jvmArgs '-noverify'
            }
        }
    }
```

もし時間できたらrobolectricなしのテストコードでもやってみたいですが、できたら共有します。

**Comment by dagezi** [comment]
@lapastillaroja nice hack!
