### ISSUE TITLE
Track Install fails

### ISSUE THREAD

**Issue by TanNTAPlus** [cyber-z/public-fox-android-sdk#120]
I implement Fox SDK 4.2 on Android.
This is SplashActivity
> 
public  void onCreate ( Bundle savedInstanceState) {
   super . OnCreate (savedInstanceState);

  // First time installation installation measurement 
  FoxTrackOption option =  new  FoxTrackOption ();
  Option . SetRedirectUrl ( " myapp: // top " )
        .setBuid (getUserId ())
        .setOptOut ( true )
        .setTrackingStateListener ( new  FoxTrackOption . TrackingStateListerner () {
            @ 
           Override public  void  onComplete () {
             Log.i("TAG", "Complete Tracking state");
           }
        });
  Fox . TrackInstall (option);
}

@Override 
protected  void onResume () {
     super . OnResume ();
     // be sure to call 
    Fox . TrackDeeplinkLaunch ( this );
}
> 
In Application
> 
 FoxConfig foxConfig = new FoxConfig(CustomApplication.this, AppConstant.FOX_APP_ID, AppConstant.FOX_APP_KEY, AppConstant.FOX_APP_SALT);
        foxConfig.addDebugOption(BuildConfig.DEBUG)
                .activate();
> 
In Android Manifest
> 
      <receiver

            android:name="co.cyberz.fox.FoxInstallReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>

> 

When i Test with http://gate-keeper.forceoperationx.com/logs
I get errors
> 
There is no log of initial start results.
Initial start results are incorrect. please confirm.
> 
I run and check has Xuniq
Who can help me?

**Comment by czendo** [comment]
Hi, @TanNTAPlus 

Thank you for contacting.

Questions about the installation procedure are accepted by our customer support.
Could you send to Customer Support your Company name, app name, and question.
Please contact your agency or sales for customer support contact information.

**Comment by TanNTAPlus** [comment]
@czendo 
When i test again, There are logs for LTV achievement, but Installation log is 
> 
There is no log of initial start results.
Initial start results are incorrect. please confirm.
>
I don't know what is problem? Can you help me

**Comment by czendo** [comment]
@TanNTAPlus 
Did you contact customer support?
If it was not yet, Please contact them.
