### ISSUE TITLE
Install Tracking not completed

### ISSUE THREAD

**Issue by TanNTAPlus** [cyber-z/public-fox-android-sdk#121]
When i implement FOX SDK 4.2.0 to Android App, i running app and show error "Install Tracking has not been completed yet."
i don't know how i am wrong? Someone help me?

**Comment by TanNTAPlus** [comment]
I implemented like that.
In Application i call

> 
  FoxConfig foxConfig = new FoxConfig(CustomApplication.this, AppConstant.FOX_APP_ID, AppConstant.FOX_APP_KEY, AppConstant.FOX_APP_SALT);
            foxConfig.addDebugOption(true)
                    .activate();
            if (14 < Build.VERSION.SDK_INT){
                registerActivityLifecycleCallbacks(new ApplicationLifeCycleCallbacks());
            }
> 
In Android Manifest:
- permission
`
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
`
- Receiver:
`
<receiver
            android:name="co.cyberz.fox.FoxInstallReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>
`
- SplashActivity
`
<activity
            android:name=".Splash"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait"
            android:launchMode="singleTop"
            android:theme="@android:style/Theme.Holo.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fox_scheme_url" />
            </intent-filter>
        </activity>
`
In SplashActivity i call

> 
 Fox.trackInstall();
> 
But Error when i get in LogCat is "E/FOX-DEBUG: Install Tracking has not been completed yet."
Please tell me why? Someone help me

**Comment by czhiraga** [comment]
@TanNTAPlus 
Thank you for the message.
This message look like an error message, but this is a trace log. It's not a problem.
This message is displayed before send measurement data.

**Comment by TanNTAPlus** [comment]
@czhiraga Thank you. I will test Measurement Data
