### ISSUE TITLE
Proguard setting?

### ISSUE THREAD

**Issue by shaunkawano** [cyber-z/public-fox-android-sdk#27]
Hi, thank you for the library.

I've tried the sdk version `3.0.0` with proguard enabled.
I've added [this proguard setting](https://github.com/cyber-z/public-fox-android-sdk/blob/master/lang/ja/README.md#7-proguardを利用する場合) to try to keep the sdk codes safe from it, yet the following error occurs while compiling:

```java
Warning:co.cyberz.dahlia.wrapper.ane.functions.BannerFunction$a: can't find referenced method 'android.app.Activity getActivity()' in program class co.cyberz.dahlia.wrapper.ane.FoxTradeContext
Warning:there were 1 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
```

Thank you in advance.

**Comment by czhiraga** [comment]
Thank you for the message.

We updated the groguard setting.
Please add the below options to your proguard conf.
```
 -keep class co.cyberz.** { *; }
 -dontwarn co.cyberz.** 
```

> [Proguard Setting](https://github.com/cyber-z/public-fox-android-sdk/blob/master/lang/ja/README.md#use_proguard)
