### ISSUE TITLE
Is there has a demo project?

### ISSUE THREAD

**Issue by ZYRzyr** [cyber-z/public-fox-android-sdk#30]
i can't import the sdk to my project.And i don't know where is the problem.So,is there has a demo project that i can use it to learn how to import the sdk to my project?

**Comment by czhiraga** [comment]
Thank you for the messaging.
Which are you using , Eclipse or Android Studio?

**Comment by ZYRzyr** [comment]
I use Eclipse

**Comment by czhiraga** [comment]
Did you copy a jar to "/libs" folder?

[Copy Jar](https://github.com/cyber-z/public-fox-android-sdk/raw/master/lang/ja/doc/integration/eclipse/img01.png)

**Comment by ZYRzyr** [comment]
Yes, I did it.

**Comment by czhiraga** [comment]
Is some error messages?
