### ISSUE TITLE
3.3.0のライセンス

### ISSUE THREAD

**Issue by hirakin** [cyber-z/public-fox-android-sdk#77]
こちら3.3.0のライセンスはどのようになっているでしょうか。

**Comment by czhiraga** [comment]
F.O.X SDKはF.O.Xの利用契約を結んでいるクライアント様を対象に無償で提供しているソフトウェアになります。
ご質問の内容は、オープンソースライセンスを意図されていると思われますが、F.O.X SDKはオープンソースソフトウェアではないため、該当するライセンスはございません。

**Comment by hiraok** [comment]
ありがとうございます。
