### ISSUE TITLE
Notification.setLatestEventInfo() is removed in API Level 23

### ISSUE THREAD

**Issue by asaejiro** [cyber-z/public-fox-android-sdk#8]
Notification.setLatestEventInfo()がAPI Level 23で削除されたようなので、対応をお願いします。

**Comment by czwuwei** [comment]
上位互換性のテストにより、setLatestEventInfoの削除にはアプリに影響ないことを既に確認できました。
確かにProguardを利用している場合、エラーが出るので、 walk-aroundとして`-dontwarn android.app.Notification`を追加すれば、回避ができます。

**Comment by asaejiro** [comment]
ご確認ありがとうございました！
-dontwarnで警告無視させていただきます。
